import type { Metadata } from "next";
import { ThemeProvider } from "@/lib/providers/theme-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import AppStateProvider from "@/lib/providers/state-provider";
import Provider from "@/lib/providers/client-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/lib/providers/socket-provider";
// import { startDb } from "@/lib/mongoDb/db";

// import sendEmail from "@/lib/email";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Where the Collaboration begins",
  description: "Generated by Harshit Thakur",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  // sendEmail("thakurranjana1979@gmail.com","hello Mummy");
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <SocketProvider>
      <AppStateProvider>
        <ThemeProvider
            attribute="class"
            defaultTheme="system">
              <Provider session={session}>
              {children}
              </Provider>
              </ThemeProvider>
              </AppStateProvider>
              </SocketProvider>
              </body>
    </html>
  );
}
